const RoutesManager = require('./routes/routesManager')
const express = require('express')
const bodyParser = require('body-parser')
const Logger = require('./logger')
const AdminPanel = require('./admin/adminsetup')